name: Optimize images

on:
  push:
    branches: [main]     # run automatically on every push to main
  pull_request:          # run when someone opens a PR
  workflow_dispatch:     # allow manual trigger

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Optimize images
        uses: calibreapp/image-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
