name: Optimize images

on:
  push:
    branches: [main]     # run automatically on every push to main
  pull_request:          # run when someone makes a pull request
  workflow_dispatch:     # allow manual trigger from Actions tab

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Optimize images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
