name: Optimize images

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Optimize images
        uses: calibreapp/image-actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
