name: Optimize images

# 👇 Give the workflow permission to push and open PRs
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # 👈 full history avoids git errors when creating branches

      - name: Optimize images
        uses: calibreapp/image-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
