name: Optimize images

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Optimize images
        uses: calibreapp/image-actions@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ← only here, not in env
